In [0]:
# Use NumPy to perform the following tasks:
# Compute the multiplication of the following matrices:
# [[1, 0], [0, 1]]
# [[1, 2], [3, 4]]

In [0]:
import numpy as np

matrix1 = np.array([[1, 0], [0, 1]])
matrix2 = np.array([[1, 2], [3, 4]])
result = np.dot(matrix1, matrix2)
print("Result of matrix multiplication:")
print(result)


Result of matrix multiplication:
[[1 2]
 [3 4]]


In [0]:
#Generate an array of length 3n filled with the cyclic pattern 1, 2, 3.

In [0]:
n = 3 
result_array = np.tile([1, 2, 3], n)
print("Resulting array:")
print(result_array)

Resulting array:
[1 2 3 1 2 3 1 2 3]


In [0]:
#Create a 10×10 matrix of zeros and then "frame" it with a border of ones.

In [0]:
matrix = np.zeros((10, 10), dtype=int)
matrix[0, :] = 1 
matrix[-1, :] = 1 
matrix[:, 0] = 1 
matrix[:, -1] = 1  

print("Resulting matrix:")
print(matrix)

Resulting matrix:
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [0]:
#Create a random 3×5 array using the np.random.rand(3, 5) function and compute: the sum of all the entries, the sum of the rows and the sum of the columns. (many Numpy functions have an optional axis= argument!)

In [0]:
random_array = np.random.rand(3, 5)
print("Random 3x5 array:")
print(random_array)

total_sum = np.sum(random_array)
print("\nSum of all entries:", total_sum)

row_sums = np.sum(random_array, axis=1)
print("\nSum of the rows:")
print(row_sums)

column_sums = np.sum(random_array, axis=0)
print("\nSum of the columns:")
print(column_sums)


Random 3x5 array:
[[0.34527787 0.9773404  0.33984475 0.54490603 0.56215825]
 [0.49945271 0.12541273 0.45631342 0.16163618 0.60224765]
 [0.63998908 0.35561858 0.38483945 0.58230988 0.18335814]]

Sum of all entries: 6.76070512344128

Sum of the rows:
[2.76952731 1.84506269 2.14611513]

Sum of the columns:
[1.48471966 1.45837172 1.18099762 1.28885208 1.34776404]


In [0]:
#Given the following arrays representing logical values (0 = False, 1 = True) compute the logical AND and logical OR operations for every pair of values of the two arrays: [1, 1, 0, 0] [1, 0, 1, 0] Hint: you may need to set the data type (dtype) of the array's elements to 'bool'

In [0]:
array1 = np.array([1, 1, 0, 0], dtype=bool)
array2 = np.array([1, 0, 1, 0], dtype=bool)

logical_and_result = np.logical_and(array1, array2)
logical_or_result = np.logical_or(array1, array2)

print("Array 1:", array1)
print("Array 2:", array2)

print("\nLogical AND result:", logical_and_result)
print("Logical OR result:", logical_or_result)

Array 1: [ True  True False False]
Array 2: [ True False  True False]

Logical AND result: [ True False False False]
Logical OR result: [ True  True  True False]


In [0]:
#Find indices of non-zero elements from [1, 2, 0, 0, 4, 0]

In [0]:
arr = np.array([1, 2, 0, 0, 4, 0])
nonzero_indices = np.nonzero(arr)

print("Indices of non-zero elements:", nonzero_indices)


Indices of non-zero elements: (array([0, 1, 4]),)


In [0]:
#Create a 8×8 array with random values and find minimum and maximum value

In [0]:
random_array = np.random.rand(8, 8)

print("Random 8x8 array:")
print(random_array)

min_value = np.min(random_array)
max_value = np.max(random_array)

print("\nMinimum value:", min_value)
print("Maximum value:", max_value)

Random 8x8 array:
[[0.56361992 0.56929459 0.12316424 0.06950598 0.9025238  0.23492062
  0.70603824 0.5536764 ]
 [0.142562   0.53840772 0.64861453 0.63901562 0.17504928 0.06636994
  0.15039704 0.41133175]
 [0.76006886 0.60165689 0.61919213 0.02247826 0.41001093 0.6696161
  0.258052   0.21846597]
 [0.62685073 0.8933021  0.45002912 0.28613689 0.52518389 0.72215804
  0.90675232 0.15680084]
 [0.93442938 0.42845861 0.79844447 0.14025868 0.38491921 0.14558803
  0.60363703 0.30757804]
 [0.58448915 0.44354288 0.48958779 0.02643719 0.48653567 0.36651618
  0.39195534 0.10688034]
 [0.42621415 0.33689437 0.91759897 0.21922163 0.89831164 0.40892496
  0.41578508 0.74557119]
 [0.71294127 0.11223949 0.45670542 0.51197272 0.69912773 0.96639194
  0.86876189 0.76241556]]

Minimum value: 0.02247826189328961
Maximum value: 0.9663919432491749


In [0]:
#Create a 8×8 array with random natural values from the range (1-100) on the diagonal, other values should be 0. Hint: You can use numpy's 'eye' function.

In [0]:
diagonal_matrix = np.eye(8, dtype=int)
random_values = np.random.randint(1, 101, size=(8, 8))
result_array = diagonal_matrix * random_values

print("Resulting 8x8 array:")
print(result_array)


Resulting 8x8 array:
[[15  0  0  0  0  0  0  0]
 [ 0  5  0  0  0  0  0  0]
 [ 0  0 85  0  0  0  0  0]
 [ 0  0  0 10  0  0  0  0]
 [ 0  0  0  0 61  0  0  0]
 [ 0  0  0  0  0 31  0  0]
 [ 0  0  0  0  0  0 21  0]
 [ 0  0  0  0  0  0  0  3]]


In [0]:
#Write a function which creates an n×n matrix with (i,j)-entry equal to i+j.

In [0]:
def create_matrix(n):
    matrix = np.fromfunction(lambda i, j: i + j, (n, n), dtype=int)
    return matrix

n = 5 #for example 5x5
result_matrix = create_matrix(n)

print(f"{n}x{n} Matrix with (i, j)-entry equal to i + j:")
print(result_matrix)

5x5 Matrix with (i, j)-entry equal to i + j:
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


In [0]:
#Write a function which creates an n×n matrix with rows having subsequent values multiplied by the row's number. For example for n = 4:
[[0, 1, 2, 3], [0, 2, 4, 6], [0, 3, 6, 9], [0, 4, 8, 12]]

In [0]:
def create_matrix(n):r
    matrix = np.fromfunction(lambda i, j: i * j, (n, n), dtype=int)
    return matrix

n = 4
result_matrix = create_matrix(n)

print(f"{n}x{n} Matrix with rows having subsequent values multiplied by the row's number:")
print(result_matrix)

4x4 Matrix with rows having subsequent values multiplied by the row's number:
[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]
 [0 3 6 9]]
